kind: pipeline
type: docker
name: Default

platform:
  os: linux
  arch: amd64

steps:

- name: tag
  image: bitnami/git
  commands:
  - git fetch --tags --verbose
  - SHA="${CI_COMMIT_SHA:0:7}"
  - TAG=$(git describe --tags --always --dirty)
  - printf "$${SHA},$${TAG}" > .tags
  - cat .tags

- name: tag-release
  image: bitnami/git
  commands:
  - git fetch --tags --verbose
  - SHA="${CI_COMMIT_SHA:0:7}"
  - TAG=$(git describe --tags --always --dirty)
  - printf "$${SHA},release-$${TAG},latest" > .tags
  - cat .tags
  when:
    event:
    - tag

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: dockerhub-pass
    repo: "${CI_REPO}"
    username: doddle
  when:
    branch:
    - master
    - develop
    - feature/*

trigger:
  branch:
  - develop
  - master
  - feature/*
  event:
  - push
  - tag

